---
AWSTemplateFormatVersion: "2010-09-09"
Description: "NLB Web Servers in TGW Workshop"

Parameters:
  EBSVolumeMaxBW:
    Description: "EBS Volume Bandwidth in MB."
    Type: Number
    MinValue: 125
    MaxValue: 1000
    Default: 250

  EBSVolumeMaxIOPs:
    Description: "EBS Volume Max IOPs."
    Type: Number
    MinValue: 3
    MaxValue: 16000
    Default: 3000


  EBSVolumeID:
    Description: "EBS Volume to Monitor."
    Type: AWS::EC2::Volume::Id
    AllowedPattern: "^[A-Za-z0-9_-]*$"
    Default: vol-0a2ddbf3ee34e7d2a

  EBSDashboardName:
    Description: "Cloudwatch Dashboard Name."
    Type: String
    AllowedPattern: "^[A-Za-z0-9_-]*$"
    Default: EBSDashboard3


Resources:
  EBSDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties: 
      DashboardBody: !Sub
        '{
            "widgets": [
                {
                    "height": 6,
                    "width": 9,
                    "y": 0,
                    "x": 0,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ { "expression": "m1/PERIOD(m1)", "label": "Read IOPs", "id": "e1", "region": "us-east-1" } ],
                            [ { "expression": "m2/PERIOD(m2)", "label": "Writes IOPs", "id": "e2", "region": "us-east-1" } ],
                            [ { "expression": "e1+e2", "label": "Total IOPs", "id": "e3", "region": "us-east-1" } ],
                            [ "AWS/EBS", "VolumeReadOps", "VolumeId", "vol-0a2ddbf3ee34e7d2a", { "id": "m1", "visible": false } ],
                            [ ".", "VolumeWriteOps", ".", ".", { "id": "m2", "visible": false } ]
                        ],
                        "view": "timeSeries",
                        "stacked": false,
                        "region": "us-east-1",
                        "stat": "Sum",
                        "period": 60,
                        "yAxis": {
                            "left": {
                                "label": "IOPS",
                                "showUnits": false
                            },
                            "right": {
                                "label": "",
                                "showUnits": false
                            }
                        },
                        "annotations": {
                            "horizontal": [
                                {
                                    "label": "IOPs Max",
                                    "value": 7800
                                }
                            ]
                        },
                        "title": "EBS IOPS"
                    }
                },
                {
                    "height": 6,
                    "width": 9,
                    "y": 0,
                    "x": 9,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ { "expression": "(m4/(1024*1024))/PERIOD(m4)", "label": "MB Read Per Second", "id": "e4", "region": "us-east-1" } ],
                            [ { "expression": "(m3/(1024*1024))/PERIOD(m3)", "label": "MB Write Per Second", "id": "e5", "region": "us-east-1" } ],
                            [ { "expression": "e4+e5", "label": "Total Consumed MB/s", "id": "e6", "region": "us-east-1" } ],
                            [ "AWS/EBS", "VolumeWriteBytes", "VolumeId", "vol-0a2ddbf3ee34e7d2a", { "id": "m3", "visible": false } ],
                            [ ".", "VolumeReadBytes", ".", ".", { "id": "m4", "visible": false } ]
                        ],
                        "view": "timeSeries",
                        "stacked": false,
                        "region": "us-east-1",
                        "stat": "Sum",
                        "period": 60,
                        "yAxis": {
                            "left": {
                                "label": "MB/s",
                                "showUnits": false
                            },
                            "right": {
                                "label": "",
                                "showUnits": false
                            }
                        },
                        "annotations": {
                            "horizontal": [
                                {
                                    "label": "BW Max",
                                    "value": 250
                                }
                            ]
                        },
                        "title": "EBS MB per Second"
                    }
                }
            ]
        }'
      DashboardName: !Ref EBSDashboardName

Outputs:
  EBSPerformanceDashboard:
    Description: "Link to CloudWatch Dashboard"
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${EBSDashboardName}"